/* Action types */
export const actionTypes = {
  LOADING_START: 'LOADING/START',
  LOADING_FINISHED: 'LOADING_FINISHED',
  // ANIME_TOP_FETCH_ERROR: 'ANIME/TOP_FETCH_ERROR',
  // ANIME_TOP_FETCH_SUCCESS: 'ANIME/TOP_FETCH_SUCCESS',
};
